-- MySQL Script generated by MySQL Workbench
-- Tue Oct 18 18:24:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`factura` (
  `idFactura` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `descripcionFactura` VARCHAR(100) NULL,
  `total` DECIMAL ZEROFILL NOT NULL,
  `idCarrito` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  UNIQUE INDEX `idFactura_UNIQUE` (`idFactura` ASC),
  UNIQUE INDEX `idCarrito_UNIQUE` (`idCarrito` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrito` (
  `idCarrito` INT NOT NULL AUTO_INCREMENT,
  `sede` VARCHAR(45) NOT NULL,
  `fechaElegida` DATETIME NOT NULL,
  `horaElegida` DATETIME NOT NULL,
  `idUsuario` INT NOT NULL,
  `idFactura` INT NOT NULL,
  `idServicio` INT NOT NULL,
  `factura_idFactura` INT NOT NULL,
  PRIMARY KEY (`idCarrito`, `factura_idFactura`),
  UNIQUE INDEX `idCarrito_UNIQUE` (`idCarrito` ASC),
  INDEX `fk_carrito_factura1_idx` (`factura_idFactura` ASC),
  UNIQUE INDEX `idServicio_UNIQUE` (`idServicio` ASC),
  CONSTRAINT `fk_carrito_factura1`
    FOREIGN KEY (`factura_idFactura`)
    REFERENCES `mydb`.`factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `idFichaMedica` VARCHAR(45) NOT NULL,
  `carrito_idCarrito` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `carrito_idCarrito`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `contraseña_UNIQUE` (`contraseña` ASC) VISIBLE,
  UNIQUE INDEX `idFichaMedica_UNIQUE` (`idFichaMedica` ASC) VISIBLE,
  INDEX `fk_usuario_carrito1_idx` (`carrito_idCarrito` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_carrito1`
    FOREIGN KEY (`carrito_idCarrito`)
    REFERENCES `mydb`.`carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ficha datos medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ficha datos medicos` (
  `idFichaMedica` INT NOT NULL AUTO_INCREMENT,
  `tipoDiabetes` TINYINT NOT NULL,
  `terapiaInsulina` TINYINT NOT NULL,
  `terapiaPastillas` TINYINT NOT NULL,
  `tipoGlucometro` VARCHAR(45) NOT NULL,
  `tipoSensor` VARCHAR(45) NOT NULL,
  `comorbilidad` VARCHAR(90) NULL,
  `objetivoGlucosa` VARCHAR(45) NOT NULL,
  `fechaNacimiento` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `idRegistroDiario` VARCHAR(45) NOT NULL,
  `usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idFichaMedica`),
  UNIQUE INDEX `idFichaMedica_UNIQUE` (`idFichaMedica` ASC),
  INDEX `fk_ficha datos medicos_usuario1_idx` (`usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_ficha datos medicos_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registros Diarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registros Diarios` (
  `id Registro Diario` INT NOT NULL AUTO_INCREMENT,
  `fechaRegistro` DATETIME NOT NULL,
  `valorGlucosa` DECIMAL ZEROFILL NOT NULL,
  `comentario` VARCHAR(60) NULL,
  `ficha datos medicos_idFichaMedica` INT NOT NULL,
  PRIMARY KEY (`id Registro Diario`),
  UNIQUE INDEX `id Registro Diario_UNIQUE` (`id Registro Diario` ASC),
  INDEX `fk_Registros Diarios_ficha datos medicos_idx` (`ficha datos medicos_idFichaMedica` ASC) VISIBLE,
  CONSTRAINT `fk_Registros Diarios_ficha datos medicos`
    FOREIGN KEY (`ficha datos medicos_idFichaMedica`)
    REFERENCES `mydb`.`ficha datos medicos` (`idFichaMedica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prestador` (
  `idPrestador` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `informacionExtra` VARCHAR(151) NOT NULL,
  PRIMARY KEY (`idPrestador`),
  UNIQUE INDEX `idPrestador_UNIQUE` (`idPrestador` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `contraseña_UNIQUE` (`contraseña` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `nombreServicio` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(150) NOT NULL,
  `sede` VARCHAR(45) NOT NULL,
  `idPrestador` INT NOT NULL,
  PRIMARY KEY (`idServicio`),
  UNIQUE INDEX `nombreServicio_UNIQUE` (`nombreServicio` ASC),
  UNIQUE INDEX `idServicio_UNIQUE` (`idServicio` ASC),
  INDEX `idPrestador_idx` (`idPrestador` ASC),
  CONSTRAINT `idPrestador`
    FOREIGN KEY (`idPrestador`)
    REFERENCES `mydb`.`prestador` (`idPrestador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCarrito`
    FOREIGN KEY (`idServicio`)
    REFERENCES `mydb`.`carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nota credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nota credito` (
  `idNota credito` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(150) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `factura_idFactura` INT NOT NULL,
  PRIMARY KEY (`idNota credito`, `factura_idFactura`),
  UNIQUE INDEX `idNota credito_UNIQUE` (`idNota credito` ASC),
  INDEX `fk_nota credito_factura1_idx` (`factura_idFactura` ASC),
  CONSTRAINT `fk_nota credito_factura1`
    FOREIGN KEY (`factura_idFactura`)
    REFERENCES `mydb`.`factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
