# Generated by Django 4.2.1 on 2023-06-05 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOneDrop', '0004_alter_paciente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='contraseña_paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email_paciente',
        ),
        migrations.RemoveField(
            model_name='prestador',
            name='contraseña_prestador',
        ),
        migrations.RemoveField(
            model_name='prestador',
            name='email_prestador',
        ),
    ]
