# Generated by Django 4.2.1 on 2023-06-16 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOneDrop', '0005_remove_paciente_contraseña_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestador',
            name='nombre_usuario_prestador',
        ),
        migrations.AddField(
            model_name='prestador',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
