# Generated by Django 4.2.1 on 2023-05-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOneDrop', '0002_rename_apellido_paciente_apellido_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_medica',
            name='comorbilidades',
            field=models.CharField(max_length=30),
        ),
    ]
