# Generated by Django 4.2.1 on 2023-05-16 21:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOneDrop', '0003_alter_ficha_medica_comorbilidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_glucemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=datetime.date.today, max_length=30)),
                ('hora_registro', models.CharField(max_length=30)),
                ('valor_glucemia', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comentario_registro', models.CharField(max_length=200)),
                ('paciente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appOneDrop.paciente')),
            ],
        ),
    ]
