# Generated by Django 4.2.1 on 2023-05-16 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOneDrop', '0004_registro_glucemia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_prestador', models.EmailField(max_length=100)),
                ('contraseña_prestador', models.CharField(max_length=50)),
                ('sede_prestador', models.CharField(max_length=50)),
                ('telefono_prestador', models.CharField(max_length=50)),
                ('informacion_extra_prestador', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email_paciente',
            field=models.EmailField(max_length=100),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=50)),
                ('descripcion_servicio', models.CharField(max_length=200)),
                ('sede_servicio', models.CharField(max_length=50)),
                ('precio_servicio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comentarios_servicio', models.CharField(max_length=200)),
                ('duracion_servicio', models.CharField(max_length=50)),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appOneDrop.prestador')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_total', models.CharField(max_length=50)),
                ('precio_total', models.CharField(max_length=50)),
                ('sede_paquete', models.CharField(max_length=50)),
                ('fecha_seleccionada', models.CharField(max_length=50)),
                ('servicio', models.ManyToManyField(to='appOneDrop.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_carrito', models.CharField(max_length=50)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appOneDrop.paciente')),
                ('servicio', models.ManyToManyField(to='appOneDrop.paquete')),
            ],
        ),
    ]
