# Generated by Django 4.2.1 on 2023-05-17 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOneDrop', '0006_alter_paciente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_glucemia',
            name='hora_registro',
        ),
    ]
