# Generated by Django 4.2.1 on 2023-05-17 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOneDrop', '0007_remove_registro_glucemia_hora_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_glucemia',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appOneDrop.paciente'),
        ),
    ]
