# Generated by Django 4.2.1 on 2023-05-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOneDrop', '0008_alter_registro_glucemia_paciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='comorbilidades',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='terapia_insulina',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='terapia_pastillas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='tipo_glucometro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='tipo_sensor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email_paciente',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='email_prestador',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='informacion_extra_prestador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registro_glucemia',
            name='comentario_registro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='comentarios_servicio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='paciente',
        ),
    ]
