# Generated by Django 4.2.1 on 2023-05-17 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appOneDrop', '0010_alter_carrito_options_alter_ficha_medica_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='fecha_seleccionada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
