# Generated by Django 4.2.1 on 2023-05-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOneDrop', '0012_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion_servicio',
            field=models.TextField(),
        ),
    ]
