# Generated by Django 4.2.1 on 2023-05-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOneDrop', '0014_alter_ficha_medica_comorbilidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='estado_carrito',
            field=models.CharField(choices=[('comprado', 'Comprado'), ('pago pendiente', 'Pago pendiente'), ('eliminado', 'Eliminado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='factura',
            name='medio_pago_factura',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('DEBITO', 'DEBITO'), ('CREDITO', 'CREDITO'), ('OTROS', 'OTROS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='terapia_insulina',
            field=models.CharField(choices=[('tipo 1', 'Tipo 1'), ('tipo 2', 'Tipo 2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='terapia_pastillas',
            field=models.CharField(choices=[('tipo 1', 'Tipo 1'), ('tipo 2', 'Tipo 2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='tipo_diabetes',
            field=models.CharField(choices=[('tipo 1', 'Tipo 1'), ('tipo 2', 'Tipo 2'), ('gestacional', 'Gestacional')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='tipo_glucometro',
            field=models.CharField(choices=[('tipo 1', 'Tipo 1'), ('tipo 2', 'Tipo 2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='tipo_sensor',
            field=models.CharField(choices=[('tipo 1', 'Tipo 1'), ('tipo 2', 'Tipo 2')], max_length=30),
        ),
    ]
