# Generated by Django 4.2.1 on 2023-05-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOneDrop', '0015_alter_carrito_estado_carrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_medica',
            name='tipo_diabetes',
            field=models.CharField(choices=[('tipo 1', 'Tipo 1'), ('tipo 2', 'Tipo 2'), ('gestacional', 'Gestacional')], max_length=35),
        ),
    ]
