# Generated by Django 4.2.1 on 2023-05-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOneDrop', '0017_alter_ficha_medica_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_medica',
            name='terapia_insulina',
            field=models.TextField(default='No'),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='terapia_pastillas',
            field=models.TextField(default='No'),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='tipo_diabetes',
            field=models.TextField(default='No'),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='tipo_glucometro',
            field=models.TextField(default='No'),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='tipo_sensor',
            field=models.TextField(default='No'),
        ),
    ]
