# Generated by Django 4.2.1 on 2023-05-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOneDrop', '0018_alter_ficha_medica_terapia_insulina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_medica',
            name='terapia_insulina',
            field=models.CharField(choices=[('tipo 1', 'Tipo 1'), ('tipo 2', 'Tipo 2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='terapia_pastillas',
            field=models.CharField(choices=[('tipo 1', 'Tipo 1'), ('tipo 2', 'Tipo 2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='tipo_diabetes',
            field=models.CharField(choices=[('tipo 1', 'Tipo 1'), ('tipo 2', 'Tipo 2'), ('gestacional', 'Gestacional')], max_length=35),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='tipo_glucometro',
            field=models.CharField(choices=[('tipo 1', 'Tipo 1'), ('tipo 2', 'Tipo 2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='tipo_sensor',
            field=models.CharField(choices=[('tipo 1', 'Tipo 1'), ('tipo 2', 'Tipo 2')], max_length=30),
        ),
    ]
